/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package example;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Breed {
  ABYSSINIAN, AMERICAN_SHORTHAIR, BIRMAN, MAINE_COON, ORIENTAL, PERSIAN, RAGDOLL, SIAMESE, SPHYNX  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Breed\",\"namespace\":\"example\",\"symbols\":[\"ABYSSINIAN\",\"AMERICAN_SHORTHAIR\",\"BIRMAN\",\"MAINE_COON\",\"ORIENTAL\",\"PERSIAN\",\"RAGDOLL\",\"SIAMESE\",\"SPHYNX\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
